server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yly
    username: root
    password: root        
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis:
  type-aliases-package: only_authority_springcloud_server.entity
  mapper-locations: classpath:mapper/**/*Mapper.xml